platform :ios, '9.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'LZPhotoBrowser_Example' do
  pod 'LZPhotoBrowser', :path => '../'

  target 'LZPhotoBrowser_Tests' do
    inherit! :search_paths

  end
end
