platform :ios, '11.0'
use_frameworks!

source 'https://cdn.cocoapods.org/'

target 'LZPhotoBrowser_Example' do
  pod 'LZPhotoBrowser', :path => '../'

  target 'LZPhotoBrowser_Tests' do
    inherit! :search_paths

  end
end
